### ISSUE TITLE
Exception on malformed input

### ISSUE THREAD

**Issue by paolsan** [alessandrolulli/reforest#4] opened 2018-09-12 16:23 UTC
When loading data that contains not well formed lines, ReForeSt launches exceptions.
I think ReForeSt must skip malformed lines and optionally log the skipped lines and / or the number of lines skipped.

The following is the exception i obtain loading a LibSVM file white letters instead of just numbers
java.lang.NumberFormatException: For input string: "185a"
	at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2043)
	at sun.misc.FloatingDecimal.parseDouble(FloatingDecimal.java:110)
	at java.lang.Double.parseDouble(Double.java:538)
	at scala.collection.immutable.StringLike$class.toDouble(StringLike.scala:285)
	at scala.collection.immutable.StringOps.toDouble(StringOps.scala:29)
	at reforest.TypeInfoDouble.fromString(TypeInfo.scala:201)
	at reforest.TypeInfoDouble.fromString(TypeInfo.scala:197)
	at reforest.data.load.LibSVMUtil$$anonfun$6.apply(LibSVMUtil.scala:77)
	at reforest.data.load.LibSVMUtil$$anonfun$6.apply(LibSVMUtil.scala:74)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
	at scala.collection.mutable.ArrayOps$ofRef.map(ArrayOps.scala:186)
	at reforest.data.load.LibSVMUtil.parseLibSVMRecord(LibSVMUtil.scala:73)
	at reforest.data.load.LibSVMUtil$$anonfun$3$$anonfun$4.apply(LibSVMUtil.scala:64)
	at reforest.data.load.LibSVMUtil$$anonfun$3$$anonfun$4.apply(LibSVMUtil.scala:64)
	at scala.collection.Iterator$$anon$11.next(Iterator.scala:410)
	at scala.collection.Iterator$$anon$11.next(Iterator.scala:410)
	at scala.collection.Iterator$$anon$13.hasNext(Iterator.scala:463)
	at org.apache.spark.util.Utils$.getIteratorSize(Utils.scala:1760)
	at org.apache.spark.rdd.RDD$$anonfun$count$1.apply(RDD.scala:1158)
	at org.apache.spark.rdd.RDD$$anonfun$count$1.apply(RDD.scala:1158)
	at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:1951)
	at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:1951)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:87)
	at org.apache.spark.scheduler.Task.run(Task.scala:99)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:322)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by alessandrolulli** [comment] 2018-09-18 10:13
I pushed a fix for this issue.
I think ReForeSt must stop if the input is malformed and, for this reason, the fix stops the execution in case of malformed input.

However, i keep this issue open because i think would be better to add a configuration variable to select if ReForeSt should skip malformed lines or stop the execution.

**Comment by alli2019** [comment] 2019-03-14 13:58
I close because the issue is resolved.

**Comment by alessandrolulli** [comment] 2019-03-14 14:00
I close because the issue is resolved

**Closed as completed by alessandrolulli** 2019-03-14 14:00 UTC
